---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: <%= ENV['CI'] ? 'junit' : 'cli' %>
  <% if ENV['CI'] %>
  output: "test-reports/%{suite}_inspec.xml"
  <% end %>

platforms:
- name: centos-6.9
  driver_config:
    box: bento/centos-6.9
    require_chef_omnibus: true
    customize:
      cpus: 2
      memory: 2048

suites:
- name: rsyslog
  run_list:
    - recipe[rsyslog]
- name: rsyslog_forward
  run_list:
    - recipe[rsyslog::forward]
  attributes:
    rsyslog:
      server_name: 1.2.3.4
- name: rsyslog_server
  run_list:
    - recipe[rsyslog::server]
  attributes:
    rsyslog:
      server_name: 1.2.3.4
