---
driver_plugin: vagrant
platforms:
- name: centos
  driver_config:
    box: opscode-centos-6.4-x86_64
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
    require_chef_omnibus: 11.4.4
    customize:
      cpus: 1
      memory: 256
    network:
      - ["private_network", { ip: "10.0.2.15" }]
suites:
- name: default
  run_list:
    - recipe[rsyslog]
    - recipe[minitest-handler]
- name: forward
  run_list:
    - recipe[rsyslog::forward]
    - recipe[minitest-handler]
  attributes:
    rsyslog:
      - server_name: '1.2.3.4'
- name: server
  run_list:
    - recipe[rsyslog::server]
    - recipe[minitest-handler]
